# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BvhipcXVampmDB5bRC7G2Y1mDOFpqena
"""

# Fixed PIN for authentication
PIN = "1234"
# Initial account balance
balance = 0
# Maximum number of PIN attempts allowed
attempts = 3

# Loop to allow PIN entry with limited attempts
while attempts > 0:
    entered_pin = input("Enter your PIN: ")

    # Check if entered PIN matches the fixed PIN
    if entered_pin == PIN:
        print("✅ Login successful!\n")

        # Keep showing menu until user chooses to exit
        while True:
            print("--- ATM Menu ---")
            print("1. Check Balance")
            print("2. Deposit Money")
            print("3. Withdraw Money")
            print("4. Exit")

            # User input for menu choice
            choice = input("Enter your choice: ")

            # Check Balance
            if choice == "1":
                print(f"💰 Your balance is: {balance}\n")

            # Deposit Money
            elif choice == "2":
                amount = int(input("Enter amount to deposit: "))
                if amount > 0:
                    balance += amount
                    print(f"✅ Deposit successful! New Balance: {balance}\n")
                else:
                    print("❌ Invalid deposit amount! Please try again.\n")

            # Withdraw Money
            elif choice == "3":
                amount = int(input("Enter amount to withdraw: "))
                if 0 < amount <= balance:
                    balance -= amount
                    print(f"✅ Withdrawal successful! New Balance: {balance}\n")
                else:
                    print("❌ Insufficient balance or invalid amount!\n")

            # Exit
            elif choice == "4":
                print("🙏 Thank you for using the ATM. Goodbye!")
                exit()  # End program

            # Invalid Menu Choice
            else:
                print("Invalid choice. Please try again.\n")

    else:
        # Decrease attempts if PIN is wrong
        attempts -= 1
        print(f"❌ Incorrect PIN! Attempts left: {attempts}")

        # If no attempts left, lock the account
        if attempts == 0:
            print("🚫 Too many incorrect attempts. Your account is locked!")