# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JdSWc6B9RDmDU_vZj7Jvr29JQX7eOAI8
"""

# SIMPLE NUMBER GUESSING GAME


# Basic Python Version

import random
print("Welcome to the Number Guessing Game 🎮")

# Computer selects a random number between 1 and 100
secret_number = random.randint(1, 100)
while True:
    # Take input from player
    guess = int(input("Enter your guess (1-100): "))
    if guess < secret_number:
        print("Too Low! Try again.")
    elif guess > secret_number:
        print("Too High! Try again.")
    else:
        print("🎉 Congratulations! You guessed it!")
        break

# OOPs Version

import random
class NumberGuessingGame:
    def __init__(self, lower=1, upper=100):
        """Initialize game with random secret number"""
        self.secret_number = random.randint(lower, upper)
        self.lower = lower
        self.upper = upper
    def play(self):
        print("Welcome to the Number Guessing Game 🎮")
        while True:
            try:
                guess = int(input(f"Enter your guess ({self.lower}-{self.upper}): "))
            except ValueError:
                print("❌ Invalid input! Please enter a number.")
                continue
            if guess < self.secret_number:
                print("Too Low! Try again.")
            elif guess > self.secret_number:
                print("Too High! Try again.")
            else:
                print("🎉 Congratulations! You guessed it!")
                break

# 🎮 Run the game
game = NumberGuessingGame()
game.play()